version: "3"

services:
    af-zipkin:
        image: openzipkin/zipkin
        ports:
            - 9411:9411
        networks:
            - afnet
    af-registry:
        image: smartcommunitylab/af-registry
        deploy:
            placement:
                constraints: [node.role == manager]
        ports:
            - 8761:8761
        networks:
            afnet:
            swarmon_net:
              aliases: 
                - prometheus-eureka-server   
    af-gateway:
        image: smartcommunitylab/af-gateway
        ports:
            - 9000:8080
        depends_on:
            - af-registry
            - af-zipkin  
        deploy:
            placement:
                 constraints: [node.role == manager]
        networks:
            - afnet
    mongo:
        image: mongo
        volumes:
            - mongo-data:/data/db
        networks:
            afnet:
              aliases:
                 - mongo
        deploy:
            placement:
                 constraints: [node.role == manager]
    af-purchase:
        image: smartcommunitylab/af-purchase:prom
        deploy:
            replicas: 2
        ports:
            - 8085:8080
        depends_on:
            - mongo
        networks:
            - afnet
    af-catalog:
        image: smartcommunitylab/af-catalog:prom
        deploy:
            replicas: 2
        ports:
            - 8080:8080
        depends_on:
            - mongo
        networks:
            - afnet
    visualizer:
        image: bretfisher/visualizer:latest
        ports:
            - "18080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                 constraints: [node.role == manager]
        networks:
            - afnet            
networks:
    swarmon_net:
        external: true
    afnet:
        driver: overlay
volumes:
    mongo-data:
